# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

### Get image
GET http://127.0.0.1:8000/img/5/0001.jpg

### Get image list
GET http://127.0.0.1:8000/list/16/